### ISSUE TITLE
Cover both Hochbrück locations

### ISSUE THREAD

**Issue by hbrgnr** [kordianbruck/TumCalProxy#18]
Hochbrück has two locations: Parkring 11-13 (e.g. https://www.ph.tum.de/about/visit/roomfinder/?room=8101.02.201) and Parkring 35-39 (e.g. https://portal.mytum.de/displayRoomMap?roomid=BC2 3.5.06@8102).
They should both be covered since currently all lectures in Parkring 35-39 are replaced by the other location.

**Comment by kordianbruck** [comment]
@hbrgnr thanks! Should be working better now - Your calendar should update within a day... 

Let me know if it works.
