### ISSUE TITLE
Lectures in rooms with number 51... are sometimes incorrect

### ISSUE THREAD

**Issue by hbrgnr** [kordianbruck/TumCalProxy#19]
The room https://www.ph.tum.de/about/visit/roomfinder/?room=5123.EG.019 gets replaced with James-Franck-Straße 1 even though it should be in Am Coulombwall 1.

I assume that there are many more such cases and I think it's very hard to cover all of them... How does the TUM Campus App handle that? Do they have precise building locations?

**Comment by hbrgnr** [comment]
FYI: according to [that](https://portal.mytum.de/campus/roomfinder/onlinehelp/sonstiges/raumfinder) the first number uniquely identifies the building. Maybe there's a list somewhere of all available buildings

**Comment by kordianbruck** [comment]
@hbrgnr thanks for the feedback. I've added a fix. 

We currently replace all 51XX building numbers with James-Franck-Str. as we assume there are multiple in the same location for the physics department. We can further add exceptions if people report them. For the TUM there are way too many build numbers and no real central list as far as I know that we could use for lookup.

**Comment by markuspi** [comment]
[TUMRoomFinder](https://campus.tum.de/tumonline/wbSuche.raumSuche) features a drop-down-list labeled 'Gebäude'. It contains a complete mapping of building numbers to address. I extracted the list [here](https://gist.github.com/markuspi/58eb54d6b41660fb629e05301de2e554).

**Comment by hbrgnr** [comment]
Nice one, I also searched for something similar but only found [that](https://portal.mytum.de/campus/roomfinder/search_room_form). Would be nice to have the corresponding city and postal code, too. Seems to be tricky though to crawl the list in the RoomFinder below the drop down menu

**Comment by kordianbruck** [comment]
@markuspi yea, thanks. I didn't think of the TUMonline room search. Any possibility you could add postal code and city to the list?

**Comment by markuspi** [comment]
Working on it :)

**Comment by markuspi** [comment]
I am ready to implement this feature. @kordianbruck do you want me to open a PR right away, or should I wait until #22 is merged since my changes interfere with yours?

**Comment by kordianbruck** [comment]
@markuspi go right ahead, we can resolve the conflicts later. I hope I can finish the docker part by end of the week.

**Comment by kordianbruck** [comment]
@markuspi thanks a lot for the fix! Looks real good :+1:
